
    .global gUnknown_08026330
gUnknown_08026330:
    .incbin "baserom.gba", 0x00026330, 0x149

    .global gUnknown_08026479
gUnknown_08026479:
    .incbin "baserom.gba", 0x00026479, 0x87

    .global MovementPatternTable
MovementPatternTable:
    .incbin "baserom.gba", 0x00026500, 0x21E85

    .global gUnknown_08048385
gUnknown_08048385:
    .incbin "baserom.gba", 0x00048385, 0x5E6E

    .global gUnknown_0804E1F3
gUnknown_0804E1F3:
    .incbin "baserom.gba", 0x0004E1F3, 0xB7A6

    .global gUnknown_08059999
gUnknown_08059999:
    .incbin "baserom.gba", 0x00059999, 0x2F14

    .global gUnknown_0805C8AD
gUnknown_0805C8AD:
    .incbin "baserom.gba", 0x0005C8AD, 0x6

    .global gUnknown_0805C8B3
gUnknown_0805C8B3:
    .incbin "baserom.gba", 0x0005C8B3, 0x2

    .global gUnknown_0805C8B5
gUnknown_0805C8B5:
    .incbin "baserom.gba", 0x0005C8B5, 0x1A

    .global gUnknown_0805C8CF
gUnknown_0805C8CF:
    .incbin "baserom.gba", 0x0005C8CF, 0x1A

    .global gUnknown_0805C8E9
gUnknown_0805C8E9:
    .incbin "baserom.gba", 0x0005C8E9, 0x96

    .global gUnknown_0805C97F
gUnknown_0805C97F:
    .incbin "baserom.gba", 0x0005C97F, 0x23

    .global gUnknown_0805C9A2
gUnknown_0805C9A2:
    .incbin "baserom.gba", 0x0005C9A2, 0x53D

    .global gUnknown_0805CEDF
gUnknown_0805CEDF:
    .incbin "baserom.gba", 0x0005CEDF, 0x18

    .global gUnknown_0805CEF7
gUnknown_0805CEF7:
    .incbin "baserom.gba", 0x0005CEF7, 0x20

    .global gUnknown_0805CF17
gUnknown_0805CF17:
    .incbin "baserom.gba", 0x0005CF17, 0x14F8

    .global gUnknown_0805E40F
gUnknown_0805E40F:
    .incbin "baserom.gba", 0x0005E40F, 0x19

    .global gUnknown_0805E428
gUnknown_0805E428:
    .incbin "baserom.gba", 0x0005E428, 0xB1F

    .global gUnknown_0805EF47
gUnknown_0805EF47:
    .incbin "baserom.gba", 0x0005EF47, 0x4E

    .global gUnknown_0805EF95
gUnknown_0805EF95:
    .incbin "baserom.gba", 0x0005EF95, 0xC57

    .global gUnknown_0805FBEC
gUnknown_0805FBEC:
    .incbin "baserom.gba", 0x0005FBEC, 0x23

    .global gUnknown_0805FC0F
gUnknown_0805FC0F:
    .incbin "baserom.gba", 0x0005FC0F, 0xAE

    .global gUnknown_0805FCBD
gUnknown_0805FCBD:
    .incbin "baserom.gba", 0x0005FCBD, 0x188

    .global gUnknown_0805FE45
gUnknown_0805FE45:
    .incbin "baserom.gba", 0x0005FE45, 0x5B

    .global gUnknown_0805FEA0
gUnknown_0805FEA0:
    .incbin "baserom.gba", 0x0005FEA0, 0xF8

    .global gUnknown_0805FF98
gUnknown_0805FF98:
    .incbin "baserom.gba", 0x0005FF98, 0x14E

    .global gUnknown_080600E6
gUnknown_080600E6:
    .incbin "baserom.gba", 0x000600E6, 0x17

    .global gUnknown_080600FD
gUnknown_080600FD:
    .incbin "baserom.gba", 0x000600FD, 0x17

    .global gUnknown_08060114
gUnknown_08060114:
    .incbin "baserom.gba", 0x00060114, 0x17

    .global gUnknown_0806012B
gUnknown_0806012B:
    .incbin "baserom.gba", 0x0006012B, 0x17

    .global gUnknown_08060142
gUnknown_08060142:
    .incbin "baserom.gba", 0x00060142, 0x1E

    .global gUnknown_08060160
gUnknown_08060160:
    .incbin "baserom.gba", 0x00060160, 0xA

    .global gUnknown_0806016A
gUnknown_0806016A:
    .incbin "baserom.gba", 0x0006016A, 0x22

    .global gUnknown_0806018C
gUnknown_0806018C:
    .incbin "baserom.gba", 0x0006018C, 0x18

    .global gUnknown_080601A4
gUnknown_080601A4:
    .incbin "baserom.gba", 0x000601A4, 0x2C

    .global gUnknown_080601D0
gUnknown_080601D0:
    .incbin "baserom.gba", 0x000601D0, 0x30

    .global gUnknown_08060200
gUnknown_08060200:
    .incbin "baserom.gba", 0x00060200, 0xF

    .global gUnknown_0806020F
gUnknown_0806020F:
    .incbin "baserom.gba", 0x0006020F, 0x10

    .global gUnknown_0806021F
gUnknown_0806021F:
    .incbin "baserom.gba", 0x0006021F, 0x1B

    .global gUnknown_0806023A
gUnknown_0806023A:
    .incbin "baserom.gba", 0x0006023A, 0x19

    .global gUnknown_08060253
gUnknown_08060253:
    .incbin "baserom.gba", 0x00060253, 0x19

    .global gUnknown_0806026C
gUnknown_0806026C:
    .incbin "baserom.gba", 0x0006026C, 0x16

    .global gUnknown_08060282
gUnknown_08060282:
    .incbin "baserom.gba", 0x00060282, 0x19

    .global gUnknown_0806029B
gUnknown_0806029B:
    .incbin "baserom.gba", 0x0006029B, 0x1C

    .global gUnknown_080602B7
gUnknown_080602B7:
    .incbin "baserom.gba", 0x000602B7, 0x17

    .global gUnknown_080602CE
gUnknown_080602CE:
    .incbin "baserom.gba", 0x000602CE, 0x1C

    .global gUnknown_080602EA
gUnknown_080602EA:
    .incbin "baserom.gba", 0x000602EA, 0x17

    .global gUnknown_08060301
gUnknown_08060301:
    .incbin "baserom.gba", 0x00060301, 0x1A

    .global gUnknown_0806031B
gUnknown_0806031B:
    .incbin "baserom.gba", 0x0006031B, 0x1B

    .global gUnknown_08060336
gUnknown_08060336:
    .incbin "baserom.gba", 0x00060336, 0x1B

    .global gUnknown_08060351
gUnknown_08060351:
    .incbin "baserom.gba", 0x00060351, 0x14

    .global gUnknown_08060365
gUnknown_08060365:
    .incbin "baserom.gba", 0x00060365, 0xF

    .global gUnknown_08060374
gUnknown_08060374:
    .incbin "baserom.gba", 0x00060374, 0x12

    .global gUnknown_08060386
gUnknown_08060386:
    .incbin "baserom.gba", 0x00060386, 0x11

    .global gUnknown_08060397
gUnknown_08060397:
    .incbin "baserom.gba", 0x00060397, 0x12

    .global gUnknown_080603A9
gUnknown_080603A9:
    .incbin "baserom.gba", 0x000603A9, 0x11

    .global gUnknown_080603BA
gUnknown_080603BA:
    .incbin "baserom.gba", 0x000603BA, 0x12

    .global gUnknown_080603CC
gUnknown_080603CC:
    .incbin "baserom.gba", 0x000603CC, 0x13

    .global gUnknown_080603DF
gUnknown_080603DF:
    .incbin "baserom.gba", 0x000603DF, 0x1E

    .global gUnknown_080603FD
gUnknown_080603FD:
    .incbin "baserom.gba", 0x000603FD, 0x1C

    .global gUnknown_08060419
gUnknown_08060419:
    .incbin "baserom.gba", 0x00060419, 0x24

    .global gUnknown_0806043D
gUnknown_0806043D:
    .incbin "baserom.gba", 0x0006043D, 0x1C

    .global gUnknown_08060459
gUnknown_08060459:
    .incbin "baserom.gba", 0x00060459, 0x24

    .global gUnknown_0806047D
gUnknown_0806047D:
    .incbin "baserom.gba", 0x0006047D, 0x19

    .global gUnknown_08060496
gUnknown_08060496:
    .incbin "baserom.gba", 0x00060496, 0x1B

    .global gUnknown_080604B1
gUnknown_080604B1:
    .incbin "baserom.gba", 0x000604B1, 0x1C

    .global gUnknown_080604CD
gUnknown_080604CD:
    .incbin "baserom.gba", 0x000604CD, 0x24

    .global gUnknown_080604F1
gUnknown_080604F1:
    .incbin "baserom.gba", 0x000604F1, 0x1D

    .global gUnknown_0806050E
gUnknown_0806050E:
    .incbin "baserom.gba", 0x0006050E, 0x1D

    .global gUnknown_0806052B
gUnknown_0806052B:
    .incbin "baserom.gba", 0x0006052B, 0x1D

    .global gUnknown_08060548
gUnknown_08060548:
    .incbin "baserom.gba", 0x00060548, 0x36

    .global gUnknown_0806057E
gUnknown_0806057E:
    .incbin "baserom.gba", 0x0006057E, 0x1C

    .global gUnknown_0806059A
gUnknown_0806059A:
    .incbin "baserom.gba", 0x0006059A, 0x18

    .global gUnknown_080605B2
gUnknown_080605B2:
    .incbin "baserom.gba", 0x000605B2, 0x1FE

    .global gUnknown_080607B0
gUnknown_080607B0:
    .incbin "baserom.gba", 0x000607B0, 0x20

    .global gUnknown_080607D0
gUnknown_080607D0:
    .incbin "baserom.gba", 0x000607D0, 0x1C

    .global gUnknown_080607EC
gUnknown_080607EC:
    .incbin "baserom.gba", 0x000607EC, 0x1A

    .global gUnknown_08060806
gUnknown_08060806:
    .incbin "baserom.gba", 0x00060806, 0x1C

    .global gUnknown_08060822
gUnknown_08060822:
    .incbin "baserom.gba", 0x00060822, 0x18

    .global gUnknown_0806083A
gUnknown_0806083A:
    .incbin "baserom.gba", 0x0006083A, 0x20

    .global gUnknown_0806085A
gUnknown_0806085A:
    .incbin "baserom.gba", 0x0006085A, 0x1B

    .global gUnknown_08060875
gUnknown_08060875:
    .incbin "baserom.gba", 0x00060875, 0x1A

    .global gUnknown_0806088F
gUnknown_0806088F:
    .incbin "baserom.gba", 0x0006088F, 0x17

    .global gUnknown_080608A6
gUnknown_080608A6:
    .incbin "baserom.gba", 0x000608A6, 0x1D

    .global gUnknown_080608C3
gUnknown_080608C3:
    .incbin "baserom.gba", 0x000608C3, 0x14

    .global gUnknown_080608D7
gUnknown_080608D7:
    .incbin "baserom.gba", 0x000608D7, 0x24

    .global gUnknown_080608FB
gUnknown_080608FB:
    .incbin "baserom.gba", 0x000608FB, 0x17

    .global gUnknown_08060912
gUnknown_08060912:
    .incbin "baserom.gba", 0x00060912, 0xD

    .global gUnknown_0806091F
gUnknown_0806091F:
    .incbin "baserom.gba", 0x0006091F, 0x1F

    .global gUnknown_0806093E
gUnknown_0806093E:
    .incbin "baserom.gba", 0x0006093E, 0x1D

    .global gUnknown_0806095B
gUnknown_0806095B:
    .incbin "baserom.gba", 0x0006095B, 0x20

    .global gUnknown_0806097B
gUnknown_0806097B:
    .incbin "baserom.gba", 0x0006097B, 0x1F

    .global gUnknown_0806099A
gUnknown_0806099A:
    .incbin "baserom.gba", 0x0006099A, 0x1E

    .global gUnknown_080609B8
gUnknown_080609B8:
    .incbin "baserom.gba", 0x000609B8, 0x1D

    .global gUnknown_080609D5
gUnknown_080609D5:
    .incbin "baserom.gba", 0x000609D5, 0x23

    .global gUnknown_080609F8
gUnknown_080609F8:
    .incbin "baserom.gba", 0x000609F8, 0x24

    .global gUnknown_08060A1C
gUnknown_08060A1C:
    .incbin "baserom.gba", 0x00060A1C, 0x1A

    .global gUnknown_08060A36
gUnknown_08060A36:
    .incbin "baserom.gba", 0x00060A36, 0x27

    .global gUnknown_08060A5D
gUnknown_08060A5D:
    .incbin "baserom.gba", 0x00060A5D, 0x28

    .global gUnknown_08060A85
gUnknown_08060A85:
    .incbin "baserom.gba", 0x00060A85, 0x22

    .global gUnknown_08060AA7
gUnknown_08060AA7:
    .incbin "baserom.gba", 0x00060AA7, 0x25

    .global gUnknown_08060ACC
gUnknown_08060ACC:
    .incbin "baserom.gba", 0x00060ACC, 0x18

    .global gUnknown_08060AE4
gUnknown_08060AE4:
    .incbin "baserom.gba", 0x00060AE4, 0x23

    .global gUnknown_08060B07
gUnknown_08060B07:
    .incbin "baserom.gba", 0x00060B07, 0x1D

    .global gUnknown_08060B24
gUnknown_08060B24:
    .incbin "baserom.gba", 0x00060B24, 0x1E

    .global gUnknown_08060B42
gUnknown_08060B42:
    .incbin "baserom.gba", 0x00060B42, 0x1A

    .global gUnknown_08060B5C
gUnknown_08060B5C:
    .incbin "baserom.gba", 0x00060B5C, 0x1B

    .global gUnknown_08060B77
gUnknown_08060B77:
    .incbin "baserom.gba", 0x00060B77, 0x1A

    .global gUnknown_08060B91
gUnknown_08060B91:
    .incbin "baserom.gba", 0x00060B91, 0x1F

    .global gUnknown_08060BB0
gUnknown_08060BB0:
    .incbin "baserom.gba", 0x00060BB0, 0x1C

    .global gUnknown_08060BCC
gUnknown_08060BCC:
    .incbin "baserom.gba", 0x00060BCC, 0x1E

    .global gUnknown_08060BEA
gUnknown_08060BEA:
    .incbin "baserom.gba", 0x00060BEA, 0x1B

    .global gUnknown_08060C05
gUnknown_08060C05:
    .incbin "baserom.gba", 0x00060C05, 0x1C

    .global gUnknown_08060C21
gUnknown_08060C21:
    .incbin "baserom.gba", 0x00060C21, 0x1D

    .global gUnknown_08060C3E
gUnknown_08060C3E:
    .incbin "baserom.gba", 0x00060C3E, 0x32

    .global gUnknown_08060C70
gUnknown_08060C70:
    .incbin "baserom.gba", 0x00060C70, 0x183

    .global gUnknown_08060DF3
gUnknown_08060DF3:
    .incbin "baserom.gba", 0x00060DF3, 0xD

    .global gUnknown_08060E00
gUnknown_08060E00:
    .incbin "baserom.gba", 0x00060E00, 0x3F

    .global gUnknown_08060E3F
gUnknown_08060E3F:
    .incbin "baserom.gba", 0x00060E3F, 0x12

    .global gUnknown_08060E51
gUnknown_08060E51:
    .incbin "baserom.gba", 0x00060E51, 0x121

    .global gUnknown_08060F72
gUnknown_08060F72:
    .incbin "baserom.gba", 0x00060F72, 0xF6

    .global gUnknown_08061068
gUnknown_08061068:
    .incbin "baserom.gba", 0x00061068, 0x1EC

    .global gUnknown_08061254
gUnknown_08061254:
    .incbin "baserom.gba", 0x00061254, 0x899

    .global gUnknown_08061AED
gUnknown_08061AED:
    .incbin "baserom.gba", 0x00061AED, 0x33

    .global gUnknown_08061B20
gUnknown_08061B20:
    .incbin "baserom.gba", 0x00061B20, 0xC7

    .global gUnknown_08061BE7
gUnknown_08061BE7:
    .incbin "baserom.gba", 0x00061BE7, 0x52

    .global gUnknown_08061C39
gUnknown_08061C39:
    .incbin "baserom.gba", 0x00061C39, 0x52

    .global gUnknown_08061C8B
gUnknown_08061C8B:
    .incbin "baserom.gba", 0x00061C8B, 0x1F

    .global gUnknown_08061CAA
gUnknown_08061CAA:
    .incbin "baserom.gba", 0x00061CAA, 0x38

    .global gUnknown_08061CE2
gUnknown_08061CE2:
    .incbin "baserom.gba", 0x00061CE2, 0x17

    .global gUnknown_08061CF9
gUnknown_08061CF9:
    .incbin "baserom.gba", 0x00061CF9, 0x11

    .global gUnknown_08061D0A
gUnknown_08061D0A:
    .incbin "baserom.gba", 0x00061D0A, 0x18

    .global gUnknown_08061D22
gUnknown_08061D22:
    .incbin "baserom.gba", 0x00061D22, 0x14

    .global gUnknown_08061D36
gUnknown_08061D36:
    .incbin "baserom.gba", 0x00061D36, 0x68

    .global gUnknown_08061D9E
gUnknown_08061D9E:
    .incbin "baserom.gba", 0x00061D9E, 0x15

    .global gUnknown_08061DB3
gUnknown_08061DB3:
    .incbin "baserom.gba", 0x00061DB3, 0x14

    .global gUnknown_08061DC7
gUnknown_08061DC7:
    .incbin "baserom.gba", 0x00061DC7, 0x50

    .global gUnknown_08061E17
gUnknown_08061E17:
    .incbin "baserom.gba", 0x00061E17, 0x1A

    .global gUnknown_08061E31
gUnknown_08061E31:
    .incbin "baserom.gba", 0x00061E31, 0x32

    .global gUnknown_08061E63
gUnknown_08061E63:
    .incbin "baserom.gba", 0x00061E63, 0x19

    .global gUnknown_08061E7C
gUnknown_08061E7C:
    .incbin "baserom.gba", 0x00061E7C, 0x14

    .global gUnknown_08061E90
gUnknown_08061E90:
    .incbin "baserom.gba", 0x00061E90, 0x18

    .global gUnknown_08061EA8
gUnknown_08061EA8:
    .incbin "baserom.gba", 0x00061EA8, 0x19

    .global gUnknown_08061EC1
gUnknown_08061EC1:
    .incbin "baserom.gba", 0x00061EC1, 0x17

    .global gUnknown_08061ED8
gUnknown_08061ED8:
    .incbin "baserom.gba", 0x00061ED8, 0x16

    .global gUnknown_08061EEE
gUnknown_08061EEE:
    .incbin "baserom.gba", 0x00061EEE, 0x19

    .global gUnknown_08061F07
gUnknown_08061F07:
    .incbin "baserom.gba", 0x00061F07, 0x15

    .global gUnknown_08061F1C
gUnknown_08061F1C:
    .incbin "baserom.gba", 0x00061F1C, 0x16

    .global gUnknown_08061F32
gUnknown_08061F32:
    .incbin "baserom.gba", 0x00061F32, 0x19

    .global gUnknown_08061F4B
gUnknown_08061F4B:
    .incbin "baserom.gba", 0x00061F4B, 0x19

    .global gUnknown_08061F64
gUnknown_08061F64:
    .incbin "baserom.gba", 0x00061F64, 0x78

    .global gUnknown_08061FDC
gUnknown_08061FDC:
    .incbin "baserom.gba", 0x00061FDC, 0x21E

    .global gUnknown_080621FA
gUnknown_080621FA:
    .incbin "baserom.gba", 0x000621FA, 0xB0F5

    .global gUnknown_0806D2EF
gUnknown_0806D2EF:
    .incbin "baserom.gba", 0x0006D2EF, 0x25E

    .global gUnknown_0806D54D
gUnknown_0806D54D:
    .incbin "baserom.gba", 0x0006D54D, 0x243

    .global gUnknown_0806D790
gUnknown_0806D790:
    .incbin "baserom.gba", 0x0006D790, 0x59AA

    .global gUnknown_0807313A
gUnknown_0807313A:
    .incbin "baserom.gba", 0x0007313A, 0x36B1

    .global gUnknown_080767EB
gUnknown_080767EB:
    .incbin "baserom.gba", 0x000767EB, 0xB0

    .global gUnknown_0807689B
gUnknown_0807689B:
    .incbin "baserom.gba", 0x0007689B, 0xD2

    .global gUnknown_0807696D
gUnknown_0807696D:
    .incbin "baserom.gba", 0x0007696D, 0x90

    .global gUnknown_080769FD
gUnknown_080769FD:
    .incbin "baserom.gba", 0x000769FD, 0xDC

    .global gUnknown_08076AD9
gUnknown_08076AD9:
    .incbin "baserom.gba", 0x00076AD9, 0x7C

    .global gUnknown_08076B55
gUnknown_08076B55:
    .incbin "baserom.gba", 0x00076B55, 0x52

    .global gUnknown_08076BA7
gUnknown_08076BA7:
    .incbin "baserom.gba", 0x00076BA7, 0x1BDD

    .global gUnknown_08078784
gUnknown_08078784:
    .incbin "baserom.gba", 0x00078784, 0xBD89

    .global gUnknown_0808450D
gUnknown_0808450D:
    .incbin "baserom.gba", 0x0008450D, 0x56

    .global gUnknown_08084563
gUnknown_08084563:
    .incbin "baserom.gba", 0x00084563, 0x11

    .global gUnknown_08084574
gUnknown_08084574:
    .incbin "baserom.gba", 0x00084574, 0x40

    .global gUnknown_080845B4
gUnknown_080845B4:
    .incbin "baserom.gba", 0x000845B4, 0x2B

    .global gUnknown_080845DF
gUnknown_080845DF:
    .incbin "baserom.gba", 0x000845DF, 0xD4

    .global gUnknown_080846B3
gUnknown_080846B3:
    .incbin "baserom.gba", 0x000846B3, 0x1A

    .global gUnknown_080846CD
gUnknown_080846CD:
    .incbin "baserom.gba", 0x000846CD, 0x2E

    .global gUnknown_080846FB
gUnknown_080846FB:
    .incbin "baserom.gba", 0x000846FB, 0x3E

    .global gUnknown_08084739
gUnknown_08084739:
    .incbin "baserom.gba", 0x00084739, 0x96

    .global gUnknown_080847CF
gUnknown_080847CF:
    .incbin "baserom.gba", 0x000847CF, 0x86

    .global gUnknown_08084855
gUnknown_08084855:
    .incbin "baserom.gba", 0x00084855, 0x24

    .global gUnknown_08084879
gUnknown_08084879:
    .incbin "baserom.gba", 0x00084879, 0x192

    .global gUnknown_08084A0B
gUnknown_08084A0B:
    .incbin "baserom.gba", 0x00084A0B, 0x8CA

    .global gUnknown_080852D5
gUnknown_080852D5:
    .incbin "baserom.gba", 0x000852D5, 0xC20

    .global gUnknown_08085EF5
gUnknown_08085EF5:
    .incbin "baserom.gba", 0x00085EF5, 0x6565

    .global gUnknown_0808C45A
gUnknown_0808C45A:
    .incbin "baserom.gba", 0x0008C45A, 0x38

    .global gUnknown_0808C492
gUnknown_0808C492:
    .incbin "baserom.gba", 0x0008C492, 0x12

    .global gUnknown_0808C4A4
gUnknown_0808C4A4:
    .incbin "baserom.gba", 0x0008C4A4, 0x1374

    .global SATURN_COFFEE_TEXT
SATURN_COFFEE_TEXT:
    .incbin "baserom.gba", 0x0008D818, 0x51A

    .global TENDA_TEA_TEXT
TENDA_TEA_TEXT:
    .incbin "baserom.gba", 0x0008DD32, 0xDE2

    .global gUnknown_0808EB14
gUnknown_0808EB14:
    .incbin "baserom.gba", 0x0008EB14, 0x11FF8

    .global TIMED_EVENT_DATA_TABLE
TIMED_EVENT_DATA_TABLE:
    .incbin "baserom.gba", 0x000A0B0C, 0x108

    .global gPhotographerConfigTable
gPhotographerConfigTable:
    .incbin "baserom.gba", 0x000A0C14, 0x900

    .global gUnknown_080A1514
gUnknown_080A1514:
    .incbin "baserom.gba", 0x000A1514, 0xA58
